version: "2"

services:
  client:
    build: ./client
    ports:
      - "3000:80" 
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "5000:5000" 
    environment:
      - NODE_ENV=production
